Repository zrock-dev/980, pull requests merged in 2023-09, with the labels that each got.

#31 fix : fixing path user json
  backend/.gitignore
  backend/src/main/java/com/fake_orgasm/users_management/repository/BTreeRepository.java
  backend/src/test/java/com/fake_orgasm/BTreeRepositoryTest.java
Labels: bug

#28 Feature/us 45 UI coin change page
  frontend/public/coin1.png
  frontend/public/coin10.png
  frontend/public/coin100.png
  frontend/public/coin2.png
  frontend/public/coin3.png
  frontend/public/coin5.png
  frontend/public/coin_img.png
  frontend/src/app/coin-change/page.js
  frontend/src/app/layout.js
  frontend/src/app/money-exchange/page.js
  frontend/src/app/page.js
  frontend/src/components/coin-change/CoinChange.js
  frontend/src/components/coin-change/CoinChangeForm.js
  frontend/src/components/coin-change/CoinChangeOperationDisplayer.js
  frontend/src/components/coin-change/CoinChangeProgressBar.js
  frontend/src/components/money-exchange/MoneyExchange.js
  frontend/src/components/navbar/Navbar.js
  frontend/src/styles/coin-change.css
Labels: feature

#38 Feature/us 46 UI creation booking system page
  frontend/public/plane-booking.svg
  frontend/src/app/booking/page.js
  frontend/src/components/booking/Booking.js
  frontend/src/components/booking/DateInput.jsx
  frontend/src/components/booking/OptionInput.jsx
  frontend/src/components/booking/PlainTextInput.jsx
  frontend/src/styles/booking.css
Labels: feature

#47 Feature/task 133/frontend communication
  frontend/src/app/page.js
  frontend/src/backend/AvailablePetitions.js
Labels: feature, infrastructure

#57 HotFix Booking service binary
  backend/booking/build.gradle
  backend/booking/gradle/wrapper/gradle-wrapper.jar
  backend/booking/gradle/wrapper/gradle-wrapper.properties
  backend/booking/gradlew
Labels: bug

#54 Feature/us 151 user searc page UI
  frontend/public/not-found-img.png
  frontend/src/app/layout.js
  frontend/src/components/navbar/Searcher.js
  frontend/src/components/user/UserSeach.jsx
  frontend/src/components/user/Users.js
  frontend/src/contexts/SearchContext.jsx
  frontend/src/styles/user-search.css
Labels: feature

#62 Queue Display
  .gitignore
  frontend/src/app/flights/page.js
  frontend/src/app/queue/page.js
  frontend/src/backend/BookingAPI.js
  frontend/src/backend/FlightsAPI.js
  frontend/src/components/booking/Booking.js
  frontend/src/components/booking/flights/FlightList.js
  frontend/src/components/booking/flights/FlightsManager.js
  frontend/src/components/booking/queue/FlightList.js
  frontend/src/components/booking/queue/ListSide.js
  frontend/src/components/booking/queue/Queue.js
  frontend/src/components/navbar/Navbar.js
  frontend/src/styles/booking/flight/column-card-item.css
  frontend/src/styles/booking/flight/list-card-item.css
  frontend/src/styles/booking/flight/pagination-button.css
  frontend/src/styles/booking/queue.css
  frontend/src/styles/booking/ticket.css
Labels: feature
