Repository zrock-dev/980, pull requests merged in 2023-08, with the labels that each got.

#3 Repository configuration
  .github/workflows/develop_workflow.yml
  backend/.idea/.gitignore
  backend/.idea/.name
  backend/.idea/compiler.xml
  backend/.idea/gradle.xml
  backend/.idea/jarRepositories.xml
  backend/.idea/misc.xml
  backend/.idea/modules.xml
  backend/.idea/vcs.xml
  backend/build.gradle
  backend/config/checkstyle/checkstyle.xml
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/settings.gradle
  backend/src/main/java/com/fake_orgasm/Application.java
  backend/src/main/java/com/fake_orgasm0/Application.java
  backend/src/test/java/com/fake_orgasm/MockUpTest.java
  backend/src/test/java/com/fake_orgasm0/ApplicationTests.java
Labels: infrastructure

#9 Feature/us 20/change based on an amount of money and total price
  .idea/.gitignore
  .idea/compiler.xml
  .idea/dbnavigator.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  backend/build.gradle
  backend/src/main/java/com/fake_orgasm/Application.java
  backend/src/main/java/com/fake_orgasm/currency_exchange/libs/maxheap/MaxHeap.java
  backend/src/main/java/com/fake_orgasm/currency_exchange/models/ExchangeRates.java
  backend/src/main/java/com/fake_orgasm/currency_exchange/models/IMoneySubtracted.java
  backend/src/main/java/com/fake_orgasm/currency_exchange/models/IntegerMoney.java
  backend/src/main/java/com/fake_orgasm/currency_exchange/services/MoneyExchanger.java
  backend/src/main/java/com/fake_orgasm/users_management/libs/btree/BTree.java
  backend/src/main/java/com/fake_orgasm/users_management/libs/btree/Node.java
  backend/src/main/java/com/fake_orgasm/users_management/models/User.java
  backend/src/main/java/com/fake_orgasm/users_management/services/IUserManagement.java
  backend/src/main/java/com/fake_orgasm/users_management/services/ServiceConfiguration.java
  backend/src/main/java/com/fake_orgasm/users_management/services/exceptions/IncompleteUserException.java
  backend/src/main/java/com/fake_orgasm/users_management/services/exceptions/InvalidPageException.java
  backend/src/test/java/com/fake_orgasm/btree/BTreeDeleteTest.java
  backend/src/test/java/com/fake_orgasm/btree/BTreeExceptions.java
  backend/src/test/java/com/fake_orgasm/btree/BTreeInsertTest.java
  backend/src/test/java/com/fake_orgasm/btree/BTreeSearchTest.java
  backend/src/test/java/com/fake_orgasm/maxheap/MaxHeapExceptions.java
  backend/src/test/java/com/fake_orgasm/maxheap/MaxHeapInsertTest.java
  backend/src/test/java/com/fake_orgasm/money_exchanger/MoneyExchangerTest.java
Labels: enhancement

#12 Feature/us 55 flight history generator
  backend/build.gradle
  backend/src/main/java/com/fake_orgasm/generator/flight_history_generator/Airport.java
  backend/src/main/java/com/fake_orgasm/generator/flight_history_generator/AirportLoader.java
  backend/src/main/java/com/fake_orgasm/generator/flight_history_generator/FlightHistory.java
  backend/src/main/java/com/fake_orgasm/generator/flight_history_generator/FlightHistoryGenerator.java
  backend/src/main/resources/airports.json
  backend/src/test/java/com/fake_orgasm/generator/AirportLoaderTest.java
  backend/src/test/java/com/fake_orgasm/generator/FlightHistoryGeneratorTest.java
Labels: enhancement

#13 chore : adding IBTreeRepository interface
  backend/src/main/java/com/fake_orgasm/users_management/repository/IBTreeRepository.java
Labels: chore

#17 User profile generator
  backend/build.gradle
  backend/config/checkstyle/checkstyle.xml
  backend/src/main/java/com/fake_orgasm/generator/user_generator/CitizenIdentificationGenerator.java
  backend/src/main/java/com/fake_orgasm/generator/user_generator/DateGenerator.java
  backend/src/main/java/com/fake_orgasm/generator/user_generator/UserGenerator.java
  backend/src/main/java/com/fake_orgasm/generator/user_generator/UserNameGenerator.java
  backend/src/main/java/com/fake_orgasm/generator/user_generator/combinatory_parts/Administrator.java
  backend/src/main/java/com/fake_orgasm/generator/user_generator/combinatory_parts/CoreWorker.java
  backend/src/main/java/com/fake_orgasm/generator/user_generator/combinatory_parts/Piece.java
  backend/src/main/java/com/fake_orgasm/generator/user_generator/combinatory_parts/Worker.java
  backend/src/main/java/com/fake_orgasm/generator/utils/FileReader.java
  backend/src/main/java/com/fake_orgasm/generator/utils/Notifiable.java
  backend/src/main/java/com/fake_orgasm/users_management/models/User.java
  backend/src/main/java/com/fake_orgasm/users_management/repository/BTreeRepository.java
  backend/src/main/java/com/fake_orgasm/users_management/repository/NodeDeserializer.java
  backend/src/main/resources/generation/first_last_name_pool.txt
  backend/src/main/resources/generation/first_name_pool.txt
  backend/src/main/resources/generation/second_last_name_pool.txt
  backend/src/main/resources/generation/second_name_pool.txt
  backend/src/test/java/com/fake_orgasm/generator/user_generator/UserGeneratorTest.java
  backend/src/test/java/com/fake_orgasm/generator/user_generator/name_generation/BasicTest.java
  backend/src/test/java/com/fake_orgasm/generator/user_generator/name_generation/FirstLastNameTest.java
  backend/src/test/java/com/fake_orgasm/generator/user_generator/name_generation/FirstNameTest.java
  backend/src/test/java/com/fake_orgasm/generator/user_generator/name_generation/SecondLastNameTest.java
  backend/src/test/java/com/fake_orgasm/generator/user_generator/name_generation/ShiftingBehaviourTest.java
  backend/src/test/java/com/fake_orgasm/generator/utils/FileReaderTest.java
  backend/src/test/java/com/fake_orgasm/generator/utils/ResourcesIntegrityTest.java
  backend/src/test/resources/generator/light_text.txt
Labels: feature

#19 CI/CD performance enhancement
  .github/workflows/develop_workflow.yml
  backend/build.gradle
Labels: enhancement
